### ISSUE TITLE
Resetting timeout unconditionally on AppendEntries request

### ISSUE THREAD

**Issue by mtn** [simonacca/zatt#3]
Hi!

I've been reading some of `zatt`'s code as I implement a toy in-memory key-value store with raft. Thank you for writing very readable code -- this has been a very helpful resource!

I notice that in `zatt/server/states.py`, you reset the election timer when the node is in a follower state before checking if the leader was up-to-date. This probably doesn't make much of a difference in practice, but wouldn't it be better to wait to reset the timer until we know that the leader was up-to-date? That way, if it isn't (i.e. the node has a more up-to-date term than the current leader) the node doesn't postpone starting an election.

It looks to me that this is how it is handled in Ongaro's pseudocode,

![screen shot 2018-06-17 at 5 01 14 pm](https://user-images.githubusercontent.com/4515110/41512563-12a38356-7250-11e8-8f2c-f8e1e16ecfb4.png)

**Comment by simonacca** [comment]
Is [this](https://github.com/simonacca/zatt/pull/4) what you mean? It's been a while since I worked on zatt but I think you are absolutely correct.

Also, thanks for the kind words :)

**Comment by mtn** [comment]
Yep, I think so :)
